# Generated by Django 4.0.6 on 2022-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='describe',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
