# Generated by Django 4.0.6 on 2022-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='describe',
        ),
        migrations.AddField(
            model_name='book',
            name='discribe',
            field=models.TextField(blank=True),
        ),
    ]
