# Generated by Django 4.0.6 on 2022-11-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_describe_book_discribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
