# Generated by Django 4.0.6 on 2022-11-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('book', '0004_rename_user_id_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(db_table='books_tags', related_name='books', to='tag.tag'),
        ),
    ]
