# Generated by Django 4.0.6 on 2022-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Seller'), (2, 'Customer')], default=0),
            preserve_default=False,
        ),
    ]
